


export const MOCK_NETWORK_USERS = [
  {
    id: "mock_user_001",
    displayName: "Amara Osei-Bonsu",
    email: "amara@example.com",
    photoURL: "https://i.pravatar.cc/150?img=47",
    headline: "Senior Product Manager at Flutterwave",
    bio: "PM building payment infrastructure for Africa. Previously Interswitch and GTBank. Accra → London → Lagos.",
    currentRole: "Senior Product Manager",
    currentCompany: "Flutterwave",
    currentCity: "Lagos",
    currentCountry: "Nigeria",
    originCity: "Accra",
    diasporaHub: "nigeria",
    skills: ["Product Strategy", "Payments", "API Products", "Roadmapping", "User Research"],
    industries: ["fintech", "payments"],
    seniority: "senior",
    yearsOfExperience: 7,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 95,
  },
  {
    id: "mock_user_002",
    displayName: "Kwame Mensah",
    email: "kwame@example.com",
    photoURL: "https://i.pravatar.cc/150?img=12",
    headline: "Software Engineer at Andela | Previously Kuda",
    bio: "Full-stack engineer passionate about building reliable systems for African markets. Kumasi → Toronto → Remote.",
    currentRole: "Software Engineer",
    currentCompany: "Andela",
    currentCity: "Toronto",
    currentCountry: "Canada",
    originCity: "Kumasi",
    diasporaHub: "canada",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    industries: ["software", "fintech"],
    seniority: "mid",
    yearsOfExperience: 5,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 88,
  },
  {
    id: "mock_user_003",
    displayName: "Chidinma Eze",
    email: "chidinma@example.com",
    photoURL: "https://i.pravatar.cc/150?img=32",
    headline: "Site Reliability Engineer at Google London",
    bio: "Making Google's infrastructure not break. Enugu → Manchester → London. YC fellowship alumna.",
    currentRole: "Site Reliability Engineer",
    currentCompany: "Google",
    currentCity: "London",
    currentCountry: "United Kingdom",
    originCity: "Enugu",
    diasporaHub: "uk",
    skills: ["Kubernetes", "Go", "Site Reliability", "Distributed Systems", "Python"],
    industries: ["software", "cloud"],
    seniority: "senior",
    yearsOfExperience: 8,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 92,
  },
  {
    id: "mock_user_004",
    displayName: "Fatima Al-Hassan",
    email: "fatima@example.com",
    photoURL: "https://i.pravatar.cc/150?img=44",
    headline: "Data Scientist at Stripe | Former M-Pesa",
    bio: "Turning African payments data into insight. Kano → Nairobi → San Francisco.",
    currentRole: "Data Scientist",
    currentCompany: "Stripe",
    currentCity: "San Francisco",
    currentCountry: "United States",
    originCity: "Kano",
    diasporaHub: "usa",
    skills: ["Python", "SQL", "Machine Learning", "Payments Analytics", "dbt"],
    industries: ["fintech", "data"],
    seniority: "senior",
    yearsOfExperience: 6,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 90,
  },
  {
    id: "mock_user_005",
    displayName: "Seun Adeyemi",
    email: "seun@example.com",
    photoURL: "https://i.pravatar.cc/150?img=15",
    headline: "Engineering Lead at Andela | Open to Advisory",
    bio: "Engineering leader at Andela for 4 years. Before that Remote.com. Lagos born, globally minded.",
    currentRole: "Engineering Lead",
    currentCompany: "Andela",
    currentCity: "Lagos",
    currentCountry: "Nigeria",
    originCity: "Lagos",
    diasporaHub: "nigeria",
    skills: ["Engineering Management", "System Architecture", "Python", "Team Building"],
    industries: ["software", "hr-tech"],
    seniority: "lead",
    yearsOfExperience: 9,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 85,
  },
  {
    id: "mock_user_006",
    displayName: "Aisha Kamara",
    email: "aisha@example.com",
    photoURL: "https://i.pravatar.cc/150?img=56",
    headline: "Product Lead at Chipper Cash",
    bio: "Building mobile money for the next billion. Freetown → Cape Town → Remote. Forbes 30 Under 30 Africa.",
    currentRole: "Product Lead",
    currentCompany: "Chipper Cash",
    currentCity: "Cape Town",
    currentCountry: "South Africa",
    originCity: "Freetown",
    diasporaHub: "south-africa",
    skills: ["Product Management", "Mobile Payments", "User Research", "OKRs", "Growth"],
    industries: ["fintech", "mobile"],
    seniority: "lead",
    yearsOfExperience: 7,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 93,
  },
  {
    id: "mock_user_007",
    displayName: "Tunde Bakare",
    email: "tunde@example.com",
    photoURL: "https://i.pravatar.cc/150?img=18",
    headline: "Senior PM at Flutterwave | ex-Paystack",
    bio: "Two-time Flutterwave and Paystack PM. Know the African payments ecosystem inside out. Lagos → Dubai.",
    currentRole: "Senior Product Manager",
    currentCompany: "Flutterwave",
    currentCity: "Dubai",
    currentCountry: "UAE",
    originCity: "Lagos",
    diasporaHub: "uae",
    skills: ["Product Management", "Fintech", "Go-to-Market", "Stakeholder Management"],
    industries: ["fintech", "payments"],
    seniority: "senior",
    yearsOfExperience: 6,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 87,
  },
  {
    id: "mock_user_008",
    displayName: "Ngozi Okonkwo",
    email: "ngozi@example.com",
    photoURL: "https://i.pravatar.cc/150?img=41",
    headline: "Analytics Engineer at Stripe",
    bio: "Data infrastructure for global payments. Onitsha → London → New York.",
    currentRole: "Analytics Engineer",
    currentCompany: "Stripe",
    currentCity: "New York",
    currentCountry: "United States",
    originCity: "Onitsha",
    diasporaHub: "usa",
    skills: ["dbt", "SQL", "Snowflake", "Python", "Data Modelling"],
    industries: ["fintech", "data"],
    seniority: "mid",
    yearsOfExperience: 4,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 82,
  },
  {
    id: "mock_user_009",
    displayName: "Kofi Asante",
    email: "kofi@example.com",
    photoURL: "https://i.pravatar.cc/150?img=65",
    headline: "People Ops Manager at Deel | Accra",
    bio: "Building distributed teams that work. Accra-based, globally connected.",
    currentRole: "People Operations Manager",
    currentCompany: "Deel",
    currentCity: "Accra",
    currentCountry: "Ghana",
    originCity: "Accra",
    diasporaHub: "ghana",
    skills: ["People Operations", "HRIS", "Recruiting", "Employment Law", "Remote Work"],
    industries: ["hr-tech", "operations"],
    seniority: "mid",
    yearsOfExperience: 5,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 80,
  },
  {
    id: "mock_user_010",
    displayName: "Zara Mohammed",
    email: "zara@example.com",
    photoURL: "https://i.pravatar.cc/150?img=49",
    headline: "Lead UX Designer at Kuda Bank | London",
    bio: "Designing financial products that earn trust. Addis Ababa → Amsterdam → London.",
    currentRole: "Lead UX Designer",
    currentCompany: "Kuda Bank",
    currentCity: "London",
    currentCountry: "United Kingdom",
    originCity: "Addis Ababa",
    diasporaHub: "uk",
    skills: ["UX Design", "Design Systems", "User Research", "Figma", "Mobile Design"],
    industries: ["fintech", "design"],
    seniority: "lead",
    yearsOfExperience: 7,
    isVerified: true,
    isMockProfile: true,
    profileCompleteness: 91,
  },
];

