export const MOCK_JOBS = [
  {
    id: "job_andela_001",
    title: "Senior Software Engineer — Full Stack",
    company: "Andela",
    companyWebsite: "https://andela.com",
    companyLogoUrl: "https://logo.clearbit.com/andela.com",
    location: "Remote — Africa",
    locationType: "remote",
    salaryMin: 60000,
    salaryMax: 90000,
    salaryCurrency: "USD",
    description: "Andela is looking for a senior full-stack engineer to join one of our distributed engineering teams. You'll work with global clients on complex technical problems. We value engineers who take ownership, communicate clearly, and build for scale. Required: 5+ years experience, React, Node.js, PostgreSQL. Preferred: experience working with global teams across time zones.",
    requirements: ["5+ years full-stack experience", "React and Node.js", "PostgreSQL or similar", "Strong async communication skills"],
    applyUrl: "https://andela.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 24) } as any,
    legitimacyScore: 97,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_002", "mock_user_005"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "remote", "africa-friendly"],
  },
  {
    id: "job_flutterwave_001",
    title: "Product Manager — Payments",
    company: "Flutterwave",
    companyWebsite: "https://flutterwave.com",
    companyLogoUrl: "https://logo.clearbit.com/flutterwave.com",
    location: "Lagos, Nigeria / Remote",
    locationType: "hybrid",
    salaryMin: 55000,
    salaryMax: 80000,
    salaryCurrency: "USD",
    description: "Flutterwave is hiring a product manager to own our core payments product. You'll work closely with engineering, design, and business development to ship features that move money for millions of Africans. We need someone who understands payments deeply, thinks in systems, and communicates clearly with both technical and non-technical stakeholders.",
    requirements: ["3+ years PM experience", "Payments or fintech background", "Strong data analysis skills", "Experience with African markets preferred"],
    applyUrl: "https://flutterwave.com/us/careers",
    source: "mock",
    scrapedAt: new Date() as any,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 12) as any,
    legitimacyScore: 96,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_001", "mock_user_007"],
    applicationCount: 0,
    isActive: true,
    tags: ["product", "fintech", "africa"],
  },
  {
    id: "job_chipper_001",
    title: "Engineering Manager",
    company: "Chipper Cash",
    companyWebsite: "https://chippercash.com",
    companyLogoUrl: "https://logo.clearbit.com/chippercash.com",
    location: "Remote — Africa / US",
    locationType: "remote",
    salaryMin: 95000,
    salaryMax: 130000,
    salaryCurrency: "USD",
    description: "Chipper Cash is hiring an engineering manager to lead a team of 6–8 engineers building our mobile money product. You'll own the technical roadmap for a core product area, hire and develop engineers, and work directly with product and design. We are a company built by Africans for Africans and we value leaders who understand our users' lived experience.",
    requirements: ["5+ years engineering", "2+ years management", "Mobile or fintech experience", "Strong hiring and mentorship track record"],
    applyUrl: "https://chippercash.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 8) } as any,
    legitimacyScore: 95,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_006"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "management", "fintech", "africa"],
  },
  {
    id: "job_kuda_001",
    title: "UX Designer — Mobile",
    company: "Kuda Bank",
    companyWebsite: "https://kuda.com",
    companyLogoUrl: "https://logo.clearbit.com/kuda.com",
    location: "Lagos, Nigeria / London, UK",
    locationType: "hybrid",
    salaryMin: 45000,
    salaryMax: 70000,
    salaryCurrency: "GBP",
    description: "Kuda is the bank of the free — built for Africans at home and in the diaspora. We are looking for a UX designer to shape the future of our mobile banking experience. You will own end-to-end design for key product areas, conduct user research with real Kuda customers, and work in a fast-paced team that ships weekly. Understanding of financial literacy challenges in the African context is essential.",
    requirements: ["3+ years UX design", "Mobile-first design experience", "Figma proficiency", "User research skills", "Understanding of African users preferred"],
    applyUrl: "https://kuda.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 20) } as any,
    legitimacyScore: 96,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_010", "mock_user_002"],
    applicationCount: 0,
    isActive: true,
    tags: ["design", "fintech", "africa", "uk"],
  },
  {
    id: "job_paystack_001",
    title: "Backend Engineer",
    company: "Paystack",
    companyWebsite: "https://paystack.com",
    companyLogoUrl: "https://logo.clearbit.com/paystack.com",
    location: "Accra, Ghana / Remote",
    locationType: "hybrid",
    salaryMin: 40000,
    salaryMax: 75000,
    salaryCurrency: "USD",
    description: "Paystack helps businesses in Africa get paid by anyone, anywhere in the world. As a Backend Engineer, you will build and maintain APIs processing millions of transactions. We are looking for engineers passionate about writing clean, maintainable code to solve hard payment infrastructure problems.",
    requirements: ["3+ years backend experience", "Node.js or Go", "Experience with scalable microservices", "Strong understanding of SQL databases"],
    applyUrl: "https://paystack.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 15) } as any,
    legitimacyScore: 98,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_001"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "fintech", "africa"],
  },
  {
    id: "job_wave_001",
    title: "Operations Manager — West Africa",
    company: "Wave",
    companyWebsite: "https://wave.com",
    companyLogoUrl: "https://logo.clearbit.com/wave.com",
    location: "Dakar, Senegal",
    locationType: "onsite",
    salaryMin: 45000,
    salaryMax: 65000,
    salaryCurrency: "USD",
    description: "Wave is making Africa the first cashless continent. We need an Operations Manager to scale our agent network aggressively across West Africa. You will manage logistics, agent liquidity, and operational troubleshooting. French fluency is highly preferred.",
    requirements: ["4+ years operations experience", "Experience managing field teams", "Strong analytical skills", "Fluent in French and English"],
    applyUrl: "https://wave.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 30) } as any,
    legitimacyScore: 95,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_006"],
    applicationCount: 0,
    isActive: true,
    tags: ["operations", "fintech", "africa"],
  },
  {
    id: "job_moniepoint_001",
    title: "Data Analyst",
    company: "Moniepoint",
    companyWebsite: "https://moniepoint.com",
    companyLogoUrl: "https://logo.clearbit.com/moniepoint.com",
    location: "Lagos, Nigeria",
    locationType: "hybrid",
    salaryMin: 25000,
    salaryMax: 45000,
    salaryCurrency: "USD",
    description: "Moniepoint is Africa's largest business payments platform. We rely heavily on data to make product and risk decisions. You will build dashboards, analyze transaction volumes, and track our credit portfolio health in real-time.",
    requirements: ["2+ years data analysis", "Advanced SQL and Python/R", "Experience with Tableau or PowerBI", "Fintech experience is a plus"],
    applyUrl: "https://moniepoint.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 18) } as any,
    legitimacyScore: 96,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_004"],
    applicationCount: 0,
    isActive: true,
    tags: ["data", "fintech", "africa"],
  },
  {
    id: "job_carbon_001",
    title: "Credit Risk Analyst",
    company: "Carbon",
    companyWebsite: "https://getcarbon.co",
    companyLogoUrl: "https://logo.clearbit.com/getcarbon.co",
    location: "Lagos, Nigeria / Remote",
    locationType: "hybrid",
    salaryMin: 30000,
    salaryMax: 50000,
    salaryCurrency: "USD",
    description: "Carbon is a pan-African digital bank. We are looking for a Credit Risk Analyst to manage our lending portfolio, optimize underwriting models, and monitor non-performing loans. You will work closely with Data Science to improve our risk algorithms.",
    requirements: ["3+ years in credit risk", "Understanding of retail lending", "Strong quantitative skills", "SQL proficiency"],
    applyUrl: "https://getcarbon.co/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 42) } as any,
    legitimacyScore: 94,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_007"],
    applicationCount: 0,
    isActive: true,
    tags: ["finance", "fintech", "africa"],
  },
  {
    id: "job_google_001",
    title: "Software Engineer III — Google Cloud",
    company: "Google",
    companyWebsite: "https://google.com",
    companyLogoUrl: "https://logo.clearbit.com/google.com",
    location: "London, UK / Remote",
    locationType: "hybrid",
    salaryMin: 110000,
    salaryMax: 160000,
    salaryCurrency: "GBP",
    description: "Join Google Cloud's infrastructure team to build the systems that power the internet. You will design and implement large-scale distributed systems, collaborate with world-class engineers, and solve problems that matter at planetary scale. We actively encourage applications from underrepresented backgrounds including candidates from African and diaspora communities.",
    requirements: ["BS/MS in Computer Science or equivalent", "3+ years software engineering", "Experience with distributed systems", "Proficiency in Go, Java, or C++"],
    applyUrl: "https://careers.google.com",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 36) } as any,
    legitimacyScore: 100,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_003"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "google", "uk", "diaspora-friendly"],
  },
  {
    id: "job_stripe_001",
    title: "Data Scientist — Emerging Markets",
    company: "Stripe",
    companyWebsite: "https://stripe.com",
    companyLogoUrl: "https://logo.clearbit.com/stripe.com",
    location: "Remote — Global",
    locationType: "remote",
    salaryMin: 120000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    description: "Stripe is expanding into emerging markets and we need a data scientist who understands these economies from the inside. You'll build machine learning models to detect fraud, analyze payment patterns, and surface insights that inform our product strategy across Africa, Southeast Asia, and Latin America.",
    requirements: ["4+ years data science", "Strong ML background", "Python and SQL proficiency", "Experience with payment or financial data"],
    applyUrl: "https://stripe.com/jobs",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 48) } as any,
    legitimacyScore: 99,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_004", "mock_user_008"],
    applicationCount: 0,
    isActive: true,
    tags: ["data", "remote", "emerging-markets"],
  },
  {
    id: "job_deel_001",
    title: "Senior People Operations Manager",
    company: "Deel",
    companyWebsite: "https://deel.com",
    companyLogoUrl: "https://logo.clearbit.com/deel.com",
    location: "Remote — Global",
    locationType: "remote",
    salaryMin: 80000,
    salaryMax: 110000,
    salaryCurrency: "USD",
    description: "Deel helps companies hire anyone anywhere. We need a senior people ops manager to help us scale our internal HR function across multiple African markets. You will manage onboarding, compliance, compensation, and culture for a fast-growing remote team. Deep knowledge of employment law in at least two African countries is required.",
    requirements: ["5+ years HR or people ops", "Experience with remote teams", "Knowledge of African employment regulations", "HRIS tools proficiency"],
    applyUrl: "https://deel.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 60) } as any,
    legitimacyScore: 98,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_009"],
    applicationCount: 0,
    isActive: true,
    tags: ["hr", "remote", "africa-expertise"],
  },
  {
    id: "job_remote_001",
    title: "Account Executive — Africa",
    company: "Remote",
    companyWebsite: "https://remote.com",
    companyLogoUrl: "https://logo.clearbit.com/remote.com",
    location: "Remote — Africa",
    locationType: "remote",
    salaryMin: 60000,
    salaryMax: 85000,
    salaryCurrency: "USD",
    description: "Remote is on a mission to make global employment accessible to everyone. We are hiring an account executive to grow our presence across Africa. You'll manage the full sales cycle, build relationships with HR leaders at tech companies expanding into African markets, and be a champion for African talent on a global stage.",
    requirements: ["3+ years B2B sales", "Based in Africa", "Existing HR or tech network in Africa", "Experience selling SaaS preferred"],
    applyUrl: "https://remote.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 70) } as any,
    legitimacyScore: 97,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_005"],
    applicationCount: 0,
    isActive: true,
    tags: ["sales", "remote", "africa-based"],
  },
  {
    id: "job_shopify_001",
    title: "Senior Frontend Engineer",
    company: "Shopify",
    companyWebsite: "https://shopify.com",
    companyLogoUrl: "https://logo.clearbit.com/shopify.com",
    location: "Remote — EMEA",
    locationType: "remote",
    salaryMin: 120000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    description: "Shopify is making commerce better for everyone. We're looking for a Senior Frontend Engineer to build resilient, accessible, and fast web applications. Our teams are distributed across time zones, and we welcome strong engineers from anywhere in EMEA, particularly those with diverse backgrounds.",
    requirements: ["5+ years frontend engineering", "Deep React and TypeScript expertise", "Experience with web performance", "Strong communication skills for remote work"],
    applyUrl: "https://shopify.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 24) } as any,
    legitimacyScore: 99,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_002"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "remote", "diaspora-friendly"],
  },
  {
    id: "job_notion_001",
    title: "Customer Success Manager — EMEA",
    company: "Notion",
    companyWebsite: "https://notion.so",
    companyLogoUrl: "https://logo.clearbit.com/notion.so",
    location: "London, UK / Remote",
    locationType: "hybrid",
    salaryMin: 70000,
    salaryMax: 95000,
    salaryCurrency: "GBP",
    description: "Notion is looking for a CSM to manage and grow our enterprise accounts across the EMEA region. You'll partner with customers to drive activation, engagement, and expansion. We highly value candidates with multicultural backgrounds who can communicate effectively across borders.",
    requirements: ["3+ years in B2B SaaS Customer Success", "Proven track record of renewals and expansion", "Strong project management skills", "Fluency in a second language is a plus"],
    applyUrl: "https://notion.so/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 50) } as any,
    legitimacyScore: 98,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_009"],
    applicationCount: 0,
    isActive: true,
    tags: ["success", "remote", "uk"],
  },
  {
    id: "job_figma_001",
    title: "Product Designer",
    company: "Figma",
    companyWebsite: "https://figma.com",
    companyLogoUrl: "https://logo.clearbit.com/figma.com",
    location: "London, UK / Remote",
    locationType: "hybrid",
    salaryMin: 80000,
    salaryMax: 120000,
    salaryCurrency: "GBP",
    description: "Figma is building the future of design and collaboration. We are looking for an exceptional Product Designer to help shape our core editing experience. You should be passionate about intuitive interactions and inclusive design.",
    requirements: ["4+ years UX/UI design", "A strong portfolio showcasing complex problem solving", "Experience building design systems", "Iterative and collaborative design approach"],
    applyUrl: "https://figma.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 40) } as any,
    legitimacyScore: 99,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_010"],
    applicationCount: 0,
    isActive: true,
    tags: ["design", "hybrid", "uk"],
  },
  {
    id: "job_intercom_001",
    title: "Software Engineer — Platform",
    company: "Intercom",
    companyWebsite: "https://intercom.com",
    companyLogoUrl: "https://logo.clearbit.com/intercom.com",
    location: "Dublin, Ireland / Remote",
    locationType: "hybrid",
    salaryMin: 80000,
    salaryMax: 110000,
    salaryCurrency: "EUR",
    description: "Intercom's platform team builds the infrastructure that powers our messaging products. We are looking for backend engineers who love scaling systems, abstracting complexity, and writing robust code in Ruby on Rails and Go.",
    requirements: ["3+ years backend engineering", "Experience with Ruby or Go", "Familiarity with distributed systems", "A passion for reliable infrastructure"],
    applyUrl: "https://intercom.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 60) } as any,
    legitimacyScore: 97,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_003"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "hybrid", "ireland"],
  },
  {
    id: "job_microsoft_001",
    title: "Principal PM",
    company: "Microsoft",
    companyWebsite: "https://microsoft.com",
    companyLogoUrl: "https://logo.clearbit.com/microsoft.com",
    location: "Seattle, WA / Remote",
    locationType: "remote",
    salaryMin: 140000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    description: "Microsoft's Azure team is looking for a Principal Product Manager to define the roadmap for our next-generation cloud security products. You will work across engineering, marketing, and sales to deliver enterprise-ready solutions.",
    requirements: ["8+ years in product management", "Experience in cloud or security products", "Strong executive communication", "Proven ability to lead cross-functional teams"],
    applyUrl: "https://careers.microsoft.com",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 10) } as any,
    legitimacyScore: 99,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_006"],
    applicationCount: 0,
    isActive: true,
    tags: ["product", "remote", "usa"],
  },
  {
    id: "job_spotify_001",
    title: "Senior Data Engineer",
    company: "Spotify",
    companyWebsite: "https://spotify.com",
    companyLogoUrl: "https://logo.clearbit.com/spotify.com",
    location: "London, UK / Remote",
    locationType: "hybrid",
    salaryMin: 90000,
    salaryMax: 120000,
    salaryCurrency: "GBP",
    description: "At Spotify, data is at the heart of everything we do. As a Senior Data Engineer, you will build data pipelines that process petabytes of music streaming data to power our recommendation engines. We want collaborative engineers who care about code quality.",
    requirements: ["5+ years data engineering", "Strong Scala or Python skills", "Experience with Hadoop or Google Cloud", "Passion for music and data"],
    applyUrl: "https://spotify.jobs",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 14) } as any,
    legitimacyScore: 98,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_008"],
    applicationCount: 0,
    isActive: true,
    tags: ["data", "hybrid", "uk"],
  },
  {
    id: "job_airbnb_001",
    title: "Trust & Safety Analyst",
    company: "Airbnb",
    companyWebsite: "https://airbnb.com",
    companyLogoUrl: "https://logo.clearbit.com/airbnb.com",
    location: "Remote — US/Canada",
    locationType: "remote",
    salaryMin: 85000,
    salaryMax: 110000,
    salaryCurrency: "USD",
    description: "Airbnb's Trust team ensures our community is safe. We are looking for an analyst to identify fraud trends, design mitigations, and improve user safety. You will analyze large datasets and collaborate with specialized risk teams.",
    requirements: ["3+ years in trust & safety or fraud", "Strong SQL skills", "Analytical problem solving", "Excellent written communication"],
    applyUrl: "https://careers.airbnb.com",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 22) } as any,
    legitimacyScore: 96,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_009"],
    applicationCount: 0,
    isActive: true,
    tags: ["analyst", "remote", "trust"],
  },
  {
    id: "job_hubspot_001",
    title: "Marketing Engineer",
    company: "HubSpot",
    companyWebsite: "https://hubspot.com",
    companyLogoUrl: "https://logo.clearbit.com/hubspot.com",
    location: "Remote — US",
    locationType: "remote",
    salaryMin: 95000,
    salaryMax: 125000,
    salaryCurrency: "USD",
    description: "HubSpot is hiring a Marketing Engineer to build the technical foundation of our growth initiatives. You will connect APIs, build custom landing page components, and optimize our marketing funnels.",
    requirements: ["3+ years frontend or full-stack experience", "JavaScript and Node.js", "Marketing tech stack familiarity", "Data-driven mindset"],
    applyUrl: "https://hubspot.com/careers",
    source: "mock",
    scrapedAt: { toDate: () => new Date() } as any,
    postedAt: { toDate: () => new Date(Date.now() - 1000 * 60 * 60 * 55) } as any,
    legitimacyScore: 97,
    legitimacyFlags: [],
    legitimacyVerdict: "approve",
    vetStatus: "approved",
    networkInsiders: ["mock_user_002"],
    applicationCount: 0,
    isActive: true,
    tags: ["engineering", "marketing", "remote"],
  }
];

